{% set name = 'py2neo' %} 
{% set version = '4.1.3' %}
{% set sha256 = '6123ead0b238662d93a308f20be728454ee6c3e0569fd5497b05fc410b2488bd' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: python -m pip install . --no-deps -vv
  entry_points:
    - py2neo = py2neo.__main__:main
  number: 0

requirements:
  build:
    - python
    - click >=7.0
    - colorama
    - neobolt <1.8,>=1.7.3
    - neotime <1.8,>=1.7.4
    - prompt_toolkit <2.1,>=2.0.7
    - pygments >=2.3.0,<2.4
    - urllib3 <1.25,>=1.23
  host:
    - pip
  run:
    - python
    - click >=2.0
    - colorama
    - neo4j-python-driver >=1.6.2,<1.7
    - neotime ==1.0.0
    - prompt_toolkit ==1.0.15
    - pygments >=2.0
    - urllib3 <1.23,>=1.21.1
test:
  imports:
    - py2neo
    - py2neo.cypher
    - py2neo.data
    - py2neo.database
    - py2neo.matching
    - py2neo.ogm
  commands:
    - py2neo 2>&1|grep py2neo


about:
  home: http://py2neo.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Python client library and toolkit for Neo4j'

extra:
  recipe-maintainers:
    - pvanheus
