{% set name = "py2neo" %} 
{% set version = "2020.1.0" %}
{% set sha256 = "b8516175af8484fcf65fc5bb98f9a6858654bb83b77e585006ca781fde583f4f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - py2neo = py2neo.__main__:main
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click >=2.0
    - colorama
    - neobolt <1.8,>=1.7.3
    - neotime <1.8,>=1.7.4
    - prompt_toolkit >=2.0.7
    - pygments >=2.3.0
    - urllib3 >=1.21.1
test:
  imports:
    - py2neo
    - py2neo.cypher
    - py2neo.data
    - py2neo.database
    - py2neo.matching
    - py2neo.ogm
  commands:
    - py2neo 2>&1|grep py2neo

about:
  home: http://py2neo.org/
  license: Apache-2.0
  license_file: LICENSE
  summary: Python client library and toolkit for Neo4j

extra:
  recipe-maintainers:
    - pvanheus
